name: deploy 

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    

    steps: 
      - name: checkout code
        uses: actions/checkout@v4
        
      - name : list
        run: ls -a

      - name: set up SSH key
        run: |
          echo "${{ secrets.LARRAVEL_KEY }}" > ssh_key.pem
          chmod 400 ssh_key.pem

      - name: deploy to ec2
        env:
          LARRAVEL_ENV: ${{secrets.LARRAVEL_ENV }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@3.110.136.243 << EOF
           set -e 

        

           # Create base directory if it doesn't exist
           sudo mkdir -p /var/www/html/laravel
          
           echo "fixing ownership"
           sudo chown -R ubuntu:ubuntu /var/www/html/laravel

            # Clone repo if not already cloned
           if [ ! -d "/var/www/html/laravel/.git" ]; then
              echo "Cloning Laravel project..."
              git clone https://github.com/Nikhilrajput-12/larravel.git /var/www/html/laravel
           else
            echo "Repo already exists. Pulling latest changes..."
            cd /var/www/html/laravel
            git pull origin main
           fi

            cd /var/www/html/laravel           

            echo "writing .env from secret"
            printf "%s\n" "$LARRAVEL_ENV" > .env

            
          
            echo "installing dependencies"
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "generating laravel app_key"
            php artisan key:generate
          
            echo "setting correct laravel permission"
            sudo chown -R www-data:www-data .
            sudo chmod -R 777 storage 

            echo "deploy complete"
          EOF
      